<?xml version="1.0"?>
<robot name="car_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Numerical Macros - units are meters and radians -->
  <xacro:property name="wheel_separation" value="0.350" /> 
  <xacro:property name="wheel_radius" value="0.100" /> 
  <xacro:property name="wheel_width"  value="0.050" />
  <xacro:property name="body_height"  value="0.200" /> 
  <xacro:property name="body_width"   value="0.250" /> 
  <xacro:property name="body_length"  value="0.500" />

   <link name="car_body">

    <visual>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}" />
      </geometry>
      <material name="Blue">
      	<color rgba="0 0.0 1.0 0.5" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0" />
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}" />
      </geometry>
    </collision>

  <inertial>
    <origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0"/> 
    <mass value="0.180"/>
    <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
  </inertial>
   </link>

   <link name="wheelR">

    <visual>
      <origin xyz="0 0 0" rpy="1.57079 0 0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <material name="Green">
      	<color rgba="0.0 1.0 0.0 0.5" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57079 0 0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>

  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.030"/>
    <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
  </inertial>
   </link>

   <link name="wheelL">

    <visual>
      <origin xyz="0 0 0" rpy="1.57079 0 0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
      <material name="Red">
      	<color rgba="1 0 0 0.5" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57079 0 0" />
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>

  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.030"/>
    <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
  </inertial>
   </link>

   <link name="suport">

    <visual>
      <origin xyz="0 0 ${-0.5 * wheel_radius}" rpy="0 0 0" />
      <geometry>
        <box size="${wheel_radius} ${wheel_radius} ${wheel_radius}" />
      </geometry>
      <material name="Blue">
      	<color rgba="0 0.0 1.0 0.5" />
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 ${-0.5 * wheel_radius}" rpy="0 0 0" />
      <geometry>
        <box size="${wheel_radius} ${wheel_radius} ${wheel_radius}" />
      </geometry>
    </collision>

  <inertial>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/> 
    <mass value="0.180"/>
    <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
  </inertial>
   </link>


   <!-- Joints -->
   <joint name="jointR" type="continuous">
    <parent link="car_body" />
    <child link="wheelR" />
    <origin xyz="${body_length * 0.25} ${-wheel_separation * 0.5} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <dynamics friction="0.0"/>
   </joint>

   <joint name="jointL" type="continuous">
    <parent link="car_body" />
    <child link="wheelL" />
    <origin xyz="${body_length * 0.25} ${+wheel_separation * 0.5} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <dynamics friction="0.0"/>
   </joint>

   <joint name="jointS" type="fixed">
    <parent link="car_body" />
    <child link="suport" />
    <origin xyz="${-body_length * 0.25} 0 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <dynamics friction="0.0"/>
   </joint>

 <gazebo reference="car_body">
   <material>Gazebo/Blue</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
 <gazebo reference="wheelR">
   <material>Gazebo/Green</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
 <gazebo reference="wheelL">
   <material>Gazebo/Red</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>    
 </gazebo>
  <gazebo reference="support">
   <material>Gazebo/Blue</material>
   <mu1>0</mu1>
   <mu2>0</mu2>    
 </gazebo>

</robot>
